<a href="https://colab.research.google.com/github/yommigold/Python_/blob/main/Working_with_Basic_Statistical_exercise_GoodBelly_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import pandas as pd
import numpy as np

In [25]:
df=pd.read_excel('GoodBelly1.xlsx')
df.head()

,Date,Region,Store,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
0,2010-05-04,FL,Biscayne (aka Aventura),150.702088,4.390000,0,0,0,0,0,1,0
1,2010-05-11,FL,Biscayne (aka Aventura),197.403797,3.997692,0,0,0,0,0,1,0
2,2010-05-18,FL,Biscayne (aka Aventura),235.106172,3.809231,0,0,0,0,0,1,0
3,2010-05-25,FL,Biscayne (aka Aventura),226.692427,3.835000,0,0,0,0,0,1,0
4,2010-06-01,FL,Biscayne (aka Aventura),257.688151,3.902500,0,0,0,0,0,1,0

In [26]:
#Q1 - Give summary of numeric type of columns in dataset?

In [27]:
df.describe()

,Units Sold,Average Retail Price,Sales Rep,Endcap,Demo,Demo1-3,Demo4-5,Natural,Fitness
count,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000,1386.000000
mean,253.820718,4.107093,0.549784,0.038240,0.058442,0.156566,0.075758,1.448773,2.476190
std,110.998731,0.463828,0.497695,0.191843,0.234661,0.363522,0.264705,0.975092,1.592789
min,47.559852,2.889286,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,189.995471,3.775714,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000
50%,236.735266,4.096667,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2.000000
75%,295.804391,4.425067,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000,4.000000
max,1041.200256,6.251538,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,5.000000

In [28]:
#Q2 Calc STD of columns in dataset

In [29]:
std_dev = df.std(axis=0)
print(std_dev)

Date                    22 days 03:27:15.853934319
Units Sold                              110.998731
Average Retail Price                      0.463828
Sales Rep                                 0.497695
Endcap                                    0.191843
Demo                                      0.234661
Demo1-3                                   0.363522
Demo4-5                                   0.264705
Natural                                   0.975092
Fitness                                   1.592789
dtype: object

<ipython-input-29-23cb31813675>:1: FutureWarning: The default value of numeric_only in DataFrame.std is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  std_dev = df.std(axis=0)

In [30]:
#Q3 mean of first 50 records in dataset

In [31]:
mean_of_first_50 = df.head(50).mean(axis=0)
print(mean_of_first_50)

Units Sold              186.280727
Average Retail Price      4.128036
Sales Rep                 0.000000
Endcap                    0.100000
Demo                      0.000000
Demo1-3                   0.000000
Demo4-5                   0.040000
Natural                   1.300000
Fitness                   1.560000
dtype: float64

<ipython-input-31-b3592bbb950b>:1: FutureWarning: DataFrame.mean and DataFrame.median with numeric_only=None will include datetime64 and datetime64tz columns in a future version.
  mean_of_first_50 = df.head(50).mean(axis=0)
<ipython-input-31-b3592bbb950b>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  mean_of_first_50 = df.head(50).mean(axis=0)

In [32]:
#Q4 What are the column names

In [33]:
print(df.columns)

Index(['Date', 'Region', 'Store', 'Units Sold', 'Average Retail Price',
       'Sales Rep', 'Endcap', 'Demo', 'Demo1-3', 'Demo4-5', 'Natural',
       'Fitness'],
      dtype='object')

In [34]:
#Q5 - Number of elements in dataset

In [35]:
number_of_elements = df.size
print(number_of_elements)

16632

In [36]:
#Q6- No. of records this dataset has

In [37]:
print(df.shape[0])

1386

In [38]:
#Q7 type of column dataset has

In [39]:
print(df.dtypes)

Date                    datetime64[ns]
Region                          object
Store                           object
Units Sold                     float64
Average Retail Price           float64
Sales Rep                        int64
Endcap                           int64
Demo                             int64
Demo1-3                          int64
Demo4-5                          int64
Natural                          int64
Fitness                          int64
dtype: object